/* eslint-disable @next/next/no-img-element */
// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home


import React from 'react'
import Header from '../components/Layouts/Header'
import Footer from '../components/Layouts/Footer'
import axios from 'axios'
import { GetServerSideProps } from 'next'
import Image from 'next/image'
import ProductCard from '../components/Shop/ProductCard'
import ErrorBoundary from '../components/Error/ErrorBoundary'
import Error from 'next/error'

export interface Product{

}

export interface HomeProps{
  products: Product[]
  topProducts:Product[]
}



export default function Home({ products, topProducts }: any) {
  console.log(topProducts)
   if (products.length===0) {
     return <Error statusCode={503}/>
   }
  
   if (topProducts.length===0) {
    return <Error statusCode={503}/>
  }
  
  
  return (
    <div className="container-fluid m-0 p-0 "style={{minHeight:"100vh"}} >
      <div className="row">
        {/* Header Start */}
        <div className="col-lg-12 ">
          <Header/>
        </div>
        </div>
        {/* Header End  */}


      {/* Main Start */}
      <div className="row ">
         <div className="col-lg-12 border border-danger "style={{padding:"0rem 5rem 0rem 5rem"}} >
          <div className="row  ">
            {/* BANNER START */}
            <div className="col-lg-12 mb-2 mt-5 ">
             <p className="">Top Products</p>
            </div>
            {topProducts.length && topProducts.map((prod:any) => {
              return (<div key={prod.id} className="col-lg-3  ">
                <img src={prod.coverImg} className="w-100 img-fluid "/>
              </div>)
            })}
            {/* BANNER END  */}
            {/*  */}
            <div className="col-lg-12 mb-2 mt-5 ">
             <p className="">All Products</p>
            </div>
            {products.map((prod: any) => (
                <ProductCard key={prod.id} product={prod}  />
            ))}
            {/*  */}
          
          </div>
        </div>
        </div>
        {/* Main End  */}


      {/* Footer Start */}
      <div className="row fixed-bottom">
        <div className="col-lg-12 m-0 p-0  " >
        </div>
          <Footer/>
        </div>
        {/* Footer End  */}
    </div>
  )
}




export const getServerSideProps: GetServerSideProps<HomeProps> = async (context) => {
  try {
    const { data: products } = await axios.get('http://127.0.0.1:7072/product');
    
    return {
      props: {
        products:products.slice(0,3),
        topProducts:products.slice(0,4)
      },
    }
  }
  catch (err:any) {
    console.log(err.message);
    return {
      props: {
        products: [],
        topProducts:[]
      },
    }
  }
 
}